version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fastapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1tkddydwkdql
      MYSQL_DATABASE: qpin
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app_network

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # JWT 설정
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here-change-in-production}
      
      # Google OAuth 설정
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-https://ec2-13-209-6-117.ap-northeast-2.compute.amazonaws.com/api/v1/auth/google/callback}
      
      # Frontend URL
      FRONTEND_URL: ${FRONTEND_URL:-https://ec2-13-209-6-117.ap-northeast-2.compute.amazonaws.com}
      
      # 데이터베이스 URL (도커 내부에서는 mysql 서비스명 사용)
      DATABASE_URL: mysql+pymysql://root:1tkddydwkdql@mysql:3306/qpin
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # 개발 시 코드 변경사항 반영
    networks:
      - app_network
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge